// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SampleTenant;

#nullable disable

namespace SampleTenant.Migrations.InvoicesDb
{
    [DbContext(typeof(InvoicesDbContext))]
    [Migration("20220503211401_Invoices")]
    partial class Invoices
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("invoices")
                .HasAnnotation("ProductVersion", "6.0.4");

            modelBuilder.Entity("SampleTenant.Model.Invoice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<string>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Total")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("InvoiceTenantIdIndex");

                    b.ToTable("Invoices", "invoices");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f38fd74b-5c0e-4747-aaf8-c39833a407da"),
                            Note = "This is a Startup invoice.",
                            TenantId = "7d706acd-f5fd-4979-9e3f-c77a0bd596b2",
                            Total = 99.95m
                        },
                        new
                        {
                            Id = new Guid("7eae891b-5d17-4e16-a918-742043d8ac7b"),
                            Note = "This is a Startup invoice.",
                            TenantId = "7d706acd-f5fd-4979-9e3f-c77a0bd596b2",
                            Total = 99.95m
                        },
                        new
                        {
                            Id = new Guid("4c86fb7a-4467-4034-988e-3d6835345823"),
                            Note = "This is a Startup invoice.",
                            TenantId = "7d706acd-f5fd-4979-9e3f-c77a0bd596b2",
                            Total = 99.95m
                        },
                        new
                        {
                            Id = new Guid("2bb87062-9c45-4b22-8d3b-3ae4b4044f60"),
                            Note = "This is a Company invoice.",
                            TenantId = "ee5128d3-4cad-4bcc-aa64-f6abbb30da46",
                            Total = 199.95m
                        },
                        new
                        {
                            Id = new Guid("9e2260df-525d-441c-94bb-63acf789700d"),
                            Note = "This is a Company invoice.",
                            TenantId = "ee5128d3-4cad-4bcc-aa64-f6abbb30da46",
                            Total = 199.95m
                        },
                        new
                        {
                            Id = new Guid("495a1d75-43cb-48c0-bcae-dd0894477a9b"),
                            Note = "This is a Company invoice.",
                            TenantId = "ee5128d3-4cad-4bcc-aa64-f6abbb30da46",
                            Total = 199.95m
                        },
                        new
                        {
                            Id = new Guid("b109560a-ccbd-42b8-b14d-3fec2b50be99"),
                            Note = "This is a Corporate invoice.",
                            TenantId = "49a049d2-23ad-41df-8806-240aebaa2f17",
                            Total = 399.95m
                        },
                        new
                        {
                            Id = new Guid("6aa993da-fe2e-4b79-8eff-8cf9a111d6ce"),
                            Note = "This is a Corporate invoice.",
                            TenantId = "49a049d2-23ad-41df-8806-240aebaa2f17",
                            Total = 399.95m
                        },
                        new
                        {
                            Id = new Guid("36701e5d-1d44-4d2e-b2a1-feeec8b4a604"),
                            Note = "This is a Corporate invoice.",
                            TenantId = "49a049d2-23ad-41df-8806-240aebaa2f17",
                            Total = 399.95m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
